//! The EPIC-80 total oracle: every one of the 2,598,960 five-card hands,
//! checked against values generated by the frozen ckc-rs 0.1.18.
//!
//! Enumeration order MUST match `tools/oracle-gen/src/main.rs` exactly:
//! nested strictly-increasing indices over the deck in `CardNumber::ALL` order.

use ckc_rs::standard52::{Card, CardNumber, Five};

const EXPECTED_HANDS: usize = 2_598_960;

fn deck() -> [Card; 52] {
    let mut deck = [Card::BLANK; 52];
    for (i, cn) in CardNumber::ALL.iter().enumerate() {
        deck[i] = Card::from(*cn as u32);
    }
    deck
}

#[test]
fn every_five_card_hand_matches_the_frozen_oracle() {
    // The fixture is ~5.2 MB and is `exclude`d from the published package, along with
    // `tools/oracle-gen` which regenerates it. This test file is NOT excluded, so it also
    // runs against an extracted `.crate` tarball (distro source builds, reproducible-build
    // harnesses, `cargo package && cargo test`). Skip there rather than hard-failing on a
    // file that was deliberately not shipped — a git checkout, where the fixture exists,
    // is the only place this test is meaningful.
    // Skipping must not become its own hollow gate: if the fixture is missing from a git
    // checkout — deleted, or never generated — this test has to FAIL, or deleting it turns
    // CI green. `tools/oracle-gen` is excluded from the package too, so its presence is a
    // reliable discriminator: tools present => git checkout => the fixture is required.
    let path = "tests/golden/five_card_ranks.bin";
    let in_git_checkout = std::path::Path::new("tools/oracle-gen/Cargo.toml").exists();

    let golden = match std::fs::read(path) {
        Ok(bytes) => bytes,
        Err(e) => {
            assert!(
                !in_git_checkout,
                "{path} is missing from a git checkout ({e}). This is the fixed point of \
                 the whole migration — regenerate it with `cargo run --manifest-path \
                 tools/oracle-gen/Cargo.toml` rather than skipping."
            );
            eprintln!(
                "SKIPPED: {path} is absent and `tools/` is absent too, so this is an \
                 extracted package rather than a checkout. Both are excluded from the \
                 published crate by design."
            );
            return;
        },
    };

    assert_eq!(golden.len(), EXPECTED_HANDS * 2, "golden file is the wrong size");

    let deck = deck();
    let mut idx = 0usize;
    let mut checked = 0usize;

    for a in 0..52 {
        for b in (a + 1)..52 {
            for c in (b + 1)..52 {
                for d in (c + 1)..52 {
                    for e in (d + 1)..52 {
                        let want = u16::from_le_bytes([golden[idx], golden[idx + 1]]);
                        let got = Five::eval([deck[a], deck[b], deck[c], deck[d], deck[e]]);
                        assert_eq!(got, want, "hand {a},{b},{c},{d},{e} — expected {want}, got {got}");
                        idx += 2;
                        checked += 1;
                    }
                }
            }
        }
    }
    assert_eq!(checked, EXPECTED_HANDS);
}
