//! The EPIC-80 total oracle: every one of the 2,598,960 five-card hands,
//! checked against values generated by the frozen ckc-rs 0.1.18.
//!
//! Enumeration order MUST match `tools/oracle-gen/src/main.rs` exactly:
//! nested strictly-increasing indices over the deck in `CardNumber::ALL` order.

use ckc_rs::standard52::{Card, CardNumber, evaluate};

const EXPECTED_HANDS: usize = 2_598_960;

fn deck() -> [Card; 52] {
    let mut deck = [Card::BLANK; 52];
    for (i, cn) in CardNumber::ALL.iter().enumerate() {
        deck[i] = Card::from(*cn as u32);
    }
    deck
}

#[test]
fn every_five_card_hand_matches_the_frozen_oracle() {
    let golden = std::fs::read("tests/golden/five_card_ranks.bin").expect("run tools/oracle-gen first");
    assert_eq!(golden.len(), EXPECTED_HANDS * 2, "golden file is the wrong size");

    let deck = deck();
    let mut idx = 0usize;
    let mut checked = 0usize;

    for a in 0..52 {
        for b in (a + 1)..52 {
            for c in (b + 1)..52 {
                for d in (c + 1)..52 {
                    for e in (d + 1)..52 {
                        let want = u16::from_le_bytes([golden[idx], golden[idx + 1]]);
                        let got = evaluate::five_cards([deck[a], deck[b], deck[c], deck[d], deck[e]]);
                        assert_eq!(got, want, "hand {a},{b},{c},{d},{e} — expected {want}, got {got}");
                        idx += 2;
                        checked += 1;
                    }
                }
            }
        }
    }
    assert_eq!(checked, EXPECTED_HANDS);
}
